# Generated by Django 4.2.21 on 2025-05-27 09:30

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_is_active_to_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created_on',
        ),
        migrations.AddField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
