
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jidyjuyniqslfviemrkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZHlqdXluaXFzbGZ2aWVtcmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTc3NTAsImV4cCI6MjA1OTY5Mzc1MH0.-OasJwtHM4h81UHJMRf_Kck3fuJFZKgm52R6OW9j_48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
