# Generated by Django 4.2.7 on 2025-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="supabase_url",
            new_name="deployment_url",
        ),
        migrations.RemoveField(
            model_name="website",
            name="supabase_id",
        ),
        migrations.AddField(
            model_name="website",
            name="analytics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="website",
            name="cookies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="website",
            name="deployment_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="last_deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
